apiVersion: v1
kind: Service
metadata:
  name: vitalhealth-service
  # Add this label so the ServiceMonitor can find this Service
  labels:
    app: vitalhealth
spec:
  selector:
    app: vitalhealth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: web  # <-- This name is required
  type: LoadBalancer
